inputs:
  app_name:
    description: 'name of the current app'
    required: true
    default: 'monarch'
  cache_version:
    description: 'version to include in cache key'
    required: false
    default: '1'
  ssh_key:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ inputs.ssh_key }}

    - name: Set up node
      uses: runslikebutter/github-workflows/actions/setup-node@v3
      with:
        app_name: ${{ inputs.app_name }}

    - name: Cache dependencies
      id: cache
      uses: runslikebutter/github-workflows/actions/cache@v3
      with:
        cache_version: ${{ inputs.cache_version }}

    - name: Install dependencies for FDS
      if: steps.cache.outputs.cache-hit != 'true' && ${{ inputs.app_name }} == 'front-desk-station'
      shell: bash
      working-directory: .
      run: yarn install --prefer-offline --network-concurrency 1

    - name: Install dependencies for Monarch
      if: steps.cache.outputs.cache-hit != 'true' && ${{ inputs.app_name }} == 'monarch'
      shell: bash
      working-directory: panel-app
      run: yarn install --prefer-offline --network-concurrency 1
