inputs:
  cache_version:
    description: "version to include in cache key"
    required: false
    default: "1"
  node_version:
    description: "the version of Node to install dependencies against"
    required: false
    default: 14.17.0
  ssh_key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ inputs.ssh_key }}

    - name: Set up node
      uses: runslikebutter/github-workflows/actions/setup-node@MET-1900
      with:
        node_version: ${{ inputs.node_version }}

    - name: Cache dependencies
      id: cache
      uses: runslikebutter/github-workflows/actions/cache@v3
      with:
        cache_version: ${{ inputs.cache_version }}

    - name: Install dependencies for FDS
      if: steps.cache.outputs.cache-hit != 'true' && inputs.node_version == '16.13.0'
      shell: bash
      working-directory: .
      run: yarn install --prefer-offline --network-concurrency 1

    - name: Install dependencies for Monarch
      if: steps.cache.outputs.cache-hit != 'true' && inputs.node_version == '14.17.0'
      shell: bash
      working-directory: panel-app
      run: yarn install --prefer-offline --network-concurrency 1
