inputs:
  ssh_key:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ inputs.ssh_key }}

    - name: Set up node
      uses: runslikebutter/github-workflows/actions/setup-node@v1

    - name: Cache dependencies
      id: cache
      uses: runslikebutter/github-workflows/actions/cache@v1

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      working-directory: panel-app
      run: yarn install --prefer-offline --network-concurrency 1
