name: Install Dependencies
description: "Install dependencies for the current project"

inputs:
  cache_version:
    default: "1"
    description: "version to include in cache key"
    required: false
  node_version:
    default: 14.17.0
    description: "the version of Node to install dependencies against"
    required: false
  ssh_key:
    description: "ssh key for bmx-access-toolkit repo"
    required: true
  working_directory:
    default: panel-app
    description: "the directory where `node_modules` will be created"
    required: false

runs:
  using: "composite"
  steps:
    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ inputs.ssh_key }}

    - name: Set up node
      uses: runslikebutter/github-workflows/actions/setup-node@MET-1900
      with:
        node_version: ${{ inputs.node_version }}

    - name: Cache dependencies
      id: cache
      uses: runslikebutter/github-workflows/actions/cache@MET-1900
      with:
        cache_version: ${{ inputs.cache_version }}
        project_root_path: ${{ inputs.working_directory }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: yarn install --prefer-offline --network-concurrency 1
