inputs:
  app-name:
    description: 'name of the current app'
    required: true
    default: 'monarch'

runs:
  using: 'composite'
  steps:
    - name: Set up node for FDS
      if: ${{ inputs.app-name }} == 'front-desk-station'
      uses: actions/setup-node@v2
      with:
        node-version: 16.13.0

    - name: Set up node for Monarch
      if: ${{ inputs.app-name }} == 'monarch'
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.0
