# inputs:
#   app_name:
#     description: 'name of the current app'
#     required: true
#     default: 'monarch'

runs:
  using: 'composite'
  steps:
    - name: Set up node for FDS
      if: env.CURRENT_APP_NAME == 'front-desk-station'
      uses: actions/setup-node@v2
      with:
        node-version: 16.13.0

    - name: Set up node for Monarch
      if: env.CURRENT_APP_NAME == 'monarch'
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.0
