inputs:
  node_version:
    description: "node version to use for the current app"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
