# hola
inputs:
  node_version:
    description: "Node version to use for the current app"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node_version }}
