name: _bump_version

on:
  workflow_call:
    inputs:
      branch:
        description: "name of the branch to version bump"
        required: false
        default: "develop"
        type: string
    outputs:
      skipped:
        description: "whether the version bump was skipped"
        value: ${{ jobs.bump_version.outputs.skipped }}
    secrets:
      GITHUB_BUILD_TOKEN:
        required: true

jobs:
  bump_version:
    name: Bump version
    runs-on: ubuntu-latest
    outputs:
      skipped: ${{ steps.bump_version.outputs.skipped }}
    steps:
    - name: Check out branch
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}

    - name: Bump version and push tag
      id: bump_version
      uses: TriPSs/conventional-changelog-action@v3
      with:
        git-message: "chore(release): {version}"
        # standard token doesn't work once the branch is a protected branch
        # github-token: ${{ secrets.github_token }}
        # use a personal access token from an admin of this repo:
        github-token: ${{ secrets.GITHUB_BUILD_TOKEN }}
        output-file: "panel-app/CHANGELOG.md"
        release-count: 15
        skip-on-empty: "true"
        version-file: "panel-app/package.json"
