name: e2e_smoke_tests
on:
  workflow_call:
    secrets:
      DOTENV:
        required: true

defaults:
  run:
    shell: bash
    working-directory: ./panel-app

jobs:
  basic-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: runslikebutter/github-workflows/actions/e2e/prep-e2e@v1
        with:
          DOTENV: ${{ secrets.DOTENV }}

      - name: ">>> Run tests ${{ github.job }}"
        id: try
        run: yarn test:e2e:headless ${{ github.job }} || echo "::set-output name=res::fail"

      - name: ">>> Retry"
        if: steps.try.outputs.res == 'fail'
        run: yarn test:e2e:headless ${{ github.job }}

      - uses: runslikebutter/github-workflows/actions/e2e/extract-logs@v1
        if: failure()

  few-pins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: runslikebutter/github-workflows/actions/e2e/prep-e2e@v1
        with:
          DOTENV: ${{ secrets.DOTENV }}

      - name: ">>> Run tests ${{ github.job }}"
        id: try
        run: yarn test:e2e:headless ${{ github.job }} || echo "::set-output name=res::fail"

      - name: ">>> Retry"
        if: steps.try.outputs.res == 'fail'
        run: yarn test:e2e:headless ${{ github.job }}

      - uses: runslikebutter/github-workflows/actions/e2e/extract-logs@v1
        if: failure()
