on:
  workflow_call:
    secrets:
      ssh_key:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: runslikebutter/github-workflows/actions/build-linux@v4
        with:
          artifact_name: dist-linux-e2e
          ssh_key: ${{ secrets.ssh_key }}
