on:
  workflow_call:
    inputs:
      branch:
        description: "name of the branch to build"
        required: false
        default: ""
        type: string
    secrets:
      ssh_key:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Build
        uses: runslikebutter/github-workflows/actions/build-linux@v4
        with:
          artifact_name: dist-linux-e2e
          ssh_key: ${{ secrets.ssh_key }}
