on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: runslikebutter/e2e
      - uses: ./.github/utils/directories

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Download Monarch executable file
        run: aws s3 cp s3://monarch-np-util/artifacts/monarch-app/develop/latest/ ~/Desktop/BMX/app --recursive --exclude "*" --include "*[!arm64].AppImage"

      - name: Upload Monarch executable as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist-linux-e2e
          path: ~/Desktop/BMX/app/*.AppImage
          if-no-files-found: error
          retention-days: 1
