on:
  workflow_call:
    secrets:
      E2E_REPO_TOKEN:
        required: false
      DOTENV:
        required: true

jobs:

##############################
# Track 1
##############################

  access-group:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: runslikebutter/e2e
          token: ${{ secrets.E2E_REPO_TOKEN || github.token }}
      - uses: ./.github/utils/prep
        with:
          DOTENV: ${{ secrets.DOTENV }}
      
      # Specific to QR tests
      - name: Install ffmpeg .deb package for QR video stream generation
        run: sudo apt update -y && sudo apt install ffmpeg -y

      - name: ">>> Run tests ${{ github.job }}"
        id: first-attempt
        run: npm run test:monarch:headless ${{ github.job }} || echo "::set-output name=res::fail"

      - name: ">>> Retry"
        if: steps.first-attempt.outputs.res == 'fail'
        run: npm run test:monarch:headless ${{ github.job }}

      - uses: ./.github/utils/extract-logs
        if: failure()

  basic-ui:
    needs: [access-group]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: runslikebutter/e2e
          token: ${{ secrets.E2E_REPO_TOKEN || github.token }}
      - uses: ./.github/utils/prep
        with:
          DOTENV: ${{ secrets.DOTENV }}

      - name: ">>> Run tests ${{ github.job }}"
        id: first-attempt
        run: npm run test:monarch:headless ${{ github.job }} || echo "::set-output name=res::fail"

      - name: ">>> Retry"
        if: steps.first-attempt.outputs.res == 'fail'
        run: npm run test:monarch:headless ${{ github.job }}

      - uses: ./.github/utils/extract-logs
        if: failure()

  commercial:
    needs: [basic-ui]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: runslikebutter/e2e
          token: ${{ secrets.E2E_REPO_TOKEN || github.token }}
      - uses: ./.github/utils/prep
        with:
          DOTENV: ${{ secrets.DOTENV }}

      - name: ">>> Run tests ${{ github.job }}"
        id: first-attempt
        run: npm run test:monarch:headless ${{ github.job }} || echo "::set-output name=res::fail"

      - name: ">>> Retry"
        if: steps.first-attempt.outputs.res == 'fail'
        run: npm run test:monarch:headless ${{ github.job }}

      - uses: ./.github/utils/extract-logs
        if: failure()

  delivery-pins:
    needs: [commercial]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: runslikebutter/e2e
          token: ${{ secrets.E2E_REPO_TOKEN || github.token }}
      - uses: ./.github/utils/prep
        with:
          DOTENV: ${{ secrets.DOTENV }}

      - name: ">>> Run tests ${{ github.job }}"
        id: first-attempt
        run: npm run test:monarch:headless ${{ github.job }} || echo "::set-output name=res::fail"

      - name: ">>> Retry"
        if: steps.first-attempt.outputs.res == 'fail'
        run: npm run test:monarch:headless ${{ github.job }}

      - uses: ./.github/utils/extract-logs
        if: failure()

  directory:
    needs: [delivery-pins]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: runslikebutter/e2e
          token: ${{ secrets.E2E_REPO_TOKEN || github.token }}
      - uses: ./.github/utils/prep
        with:
          DOTENV: ${{ secrets.DOTENV }}

      - name: ">>> Run tests ${{ github.job }}"
        id: first-attempt
        run: npm run test:monarch:headless ${{ github.job }} || echo "::set-output name=res::fail"

      - name: ">>> Retry"
        if: steps.first-attempt.outputs.res == 'fail'
        run: npm run test:monarch:headless ${{ github.job }}

      - uses: ./.github/utils/extract-logs
        if: failure()

  door-pins:
    needs: [directory]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: runslikebutter/e2e
          token: ${{ secrets.E2E_REPO_TOKEN || github.token }}
      - uses: ./.github/utils/prep
        with:
          DOTENV: ${{ secrets.DOTENV }}

      - name: ">>> Run tests ${{ github.job }}"
        id: first-attempt
        run: npm run test:monarch:headless ${{ github.job }} || echo "::set-output name=res::fail"

      - name: ">>> Retry"
        if: steps.first-attempt.outputs.res == 'fail'
        run: npm run test:monarch:headless ${{ github.job }}

      - uses: ./.github/utils/extract-logs
        if: failure()

  home-page:
    needs: [door-pins]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: runslikebutter/e2e
          token: ${{ secrets.E2E_REPO_TOKEN || github.token }}
      - uses: ./.github/utils/prep
        with:
          DOTENV: ${{ secrets.DOTENV }}

      - name: ">>> Run tests ${{ github.job }}"
        id: first-attempt
        run: npm run test:monarch:headless ${{ github.job }} || echo "::set-output name=res::fail"

      - name: ">>> Retry"
        if: steps.first-attempt.outputs.res == 'fail'
        run: npm run test:monarch:headless ${{ github.job }}

      - uses: ./.github/utils/extract-logs
        if: failure()


##############################
# Track 2
##############################

  inactive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: runslikebutter/e2e
          token: ${{ secrets.E2E_REPO_TOKEN || github.token }}
      - uses: ./.github/utils/prep
        with:
          DOTENV: ${{ secrets.DOTENV }}

      - name: ">>> Run tests ${{ github.job }}"
        id: first-attempt
        run: npm run test:monarch:headless ${{ github.job }} || echo "::set-output name=res::fail"

      - name: ">>> Retry"
        if: steps.first-attempt.outputs.res == 'fail'
        run: npm run test:monarch:headless ${{ github.job }}

      - uses: ./.github/utils/extract-logs
        if: failure()

  package-room:
    needs: [inactive]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: runslikebutter/e2e
          token: ${{ secrets.E2E_REPO_TOKEN || github.token }}
      - uses: ./.github/utils/prep
        with:
          DOTENV: ${{ secrets.DOTENV }}

      - name: ">>> Run tests ${{ github.job }}"
        id: first-attempt
        run: npm run test:monarch:headless ${{ github.job }} || echo "::set-output name=res::fail"

      - name: ">>> Retry"
        if: steps.first-attempt.outputs.res == 'fail'
        run: npm run test:monarch:headless ${{ github.job }}

      - uses: ./.github/utils/extract-logs
        if: failure()

  qr:
    needs: [package-room]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: runslikebutter/e2e
          token: ${{ secrets.E2E_REPO_TOKEN || github.token }}
      - uses: ./.github/utils/prep
        with:
          DOTENV: ${{ secrets.DOTENV }}
      
      # Specific to QR tests
      - name: Install ffmpeg .deb package for QR video stream generation
        run: sudo apt update -y && sudo apt install ffmpeg -y

      - name: ">>> Run tests ${{ github.job }}"
        id: first-attempt
        run: npm run test:monarch:headless ${{ github.job }} || echo "::set-output name=res::fail"

      - name: ">>> Retry"
        if: steps.first-attempt.outputs.res == 'fail'
        run: npm run test:monarch:headless ${{ github.job }}

      - uses: ./.github/utils/extract-logs
        if: failure()

  relays:
    needs: [qr]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: runslikebutter/e2e
          token: ${{ secrets.E2E_REPO_TOKEN || github.token }}
      - uses: ./.github/utils/prep
        with:
          DOTENV: ${{ secrets.DOTENV }}

      - name: ">>> Run tests ${{ github.job }}"
        id: first-attempt
        run: npm run test:monarch:headless ${{ github.job }} || echo "::set-output name=res::fail"

      - name: ">>> Retry"
        if: steps.first-attempt.outputs.res == 'fail'
        run: npm run test:monarch:headless ${{ github.job }}

      - uses: ./.github/utils/extract-logs
        if: failure()

  vk-pins:
    needs: [relays]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: runslikebutter/e2e
          token: ${{ secrets.E2E_REPO_TOKEN || github.token }}
      - uses: ./.github/utils/prep
        with:
          DOTENV: ${{ secrets.DOTENV }}

      - name: ">>> Run tests ${{ github.job }}"
        id: first-attempt
        run: npm run test:monarch:headless ${{ github.job }} || echo "::set-output name=res::fail"

      - name: ">>> Retry"
        if: steps.first-attempt.outputs.res == 'fail'
        run: npm run test:monarch:headless ${{ github.job }}

      - uses: ./.github/utils/extract-logs
        if: failure()

  zones:
    needs: [vk-pins]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: runslikebutter/e2e
          token: ${{ secrets.E2E_REPO_TOKEN || github.token }}
      - uses: ./.github/utils/prep
        with:
          DOTENV: ${{ secrets.DOTENV }}

      - name: ">>> Run tests ${{ github.job }}"
        id: first-attempt
        run: npm run test:monarch:headless ${{ github.job }} || echo "::set-output name=res::fail"

      - name: ">>> Retry"
        if: steps.first-attempt.outputs.res == 'fail'
        run: npm run test:monarch:headless ${{ github.job }}

      - uses: ./.github/utils/extract-logs
        if: failure()
